Repository aldalgl/Proyek-Visualisasi-Data-SYCACA-ACRAB, pull requests merged in 2021-12, with the labels that each got.

#10 Create Panel Visualisasi 2a.png
  03 Panel Visualisasi/Panel Visualisasi 2a.png
Labels: documentation

#11 Create Panel Visualisasi 2b
  03 Panel Visualisasi/Panel Visualisasi 2b.png
Labels: documentation, enhancement

#12 Create Dokumen Proposal
  01 Proposal/SYCACA ACRAB-PRO-VISDAT-GSL-21-22.pdf
Labels: documentation

#14 Panel 1
  03 Panel Visualisasi/Panel Visualisasi 1.png
Labels: documentation

#15 Create Panel Visualisasi 3,png
  03 Panel Visualisasi/Panel Visualisasi 3.png
Labels: enhancement

#17 Create Laporan Proyek
  .DS_Store
  02 Laporan Proyek/SYCACA ACRAB-LAP-VISDAT-GSL-21-22.pdf
Labels: enhancement

#16 Create Panel Dashboard
  .gitignore
  03 Panel Visualisasi/Panel Dashboard.png
Labels: enhancement

#18 Create hasil evaluasi
  04 Hasil Evaluasi/Analisis Visualisasi Netflix Movies and TV Shows (Responses).xlsx
  04 Hasil Evaluasi/Evaluasi Pertanyaan 1.PNG
  04 Hasil Evaluasi/Evaluasi Pertanyaan 2.PNG
Labels: documentation
